version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      MAINTAINER: '@akshat28'
      VENDOR: 'ASUS'
      CODENAME: 'X00T'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      CHANGELOG: |
        - Bringup 3.0 
        - Source side changes 
        - Fully Redesigned UI 
        - New Android like Power Menu (Activated via power key hold) 
        - Flashlight toggled by Vol up(+) on hold 
        - Flashlight toggle on Lockscreen 
        - Etc.
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: Shinchan
